name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0, 3.1, 3.2, 3.3, 3.4]
    steps:
      - name: Set up SSH key for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CI_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.ruby-version }}" == "2.6" ]]; then
            gem install bundler -v 2.6
          else
            gem install bundler
          fi
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bundle exec rspec --color --format documentation spec

